### ISSUE TITLE
Server Rejects Request - Access Token

### ISSUE THREAD

**Issue by nickkos101** [Greyght/mobiniti-api-client-php#1]
Fatal error: Uncaught Mobiniti\Api\Exceptions\Http\UnauthorizedException: The server denied the request. 

Where access token is located I tried pasting my key and secret generated in the mobiniti settings page. It still wont authorize the request is the access token generated differently?

```
function test_mobi() {
  $mobiniti = new \Mobiniti\Api\Client('ACCESS_TOKEN');
  $test = $mobiniti->contacts()->all(10, 1);
  print_r($test);
}

test_mobi();
```

**Comment by jgodish** [comment]
Hi Nick,
I see a redirect url but it looks like it is a local dev environment so that could be part of the problem. Did you go through the entire oauth process and get an access token?
